deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PERSONAL_ACCESS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  target-branch: gh-pages
  on:
    branch: master